package tech.coner.trailer.render.eventresults

import tech.coner.trailer.eventresults.ComprehensiveEventResults

interface ComprehensiveEventResultsRenderer : EventResultsRenderer<ComprehensiveEventResults>