name: CI

on: [push, pull_request]

jobs:
  ci-jvm:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Verify
        run: ./mvnw -T 1C -P ci verify
